#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

HOST=lab1

ssh "$HOST" systemctl --user stop khutulun-agent.service || true

# Note: copying the file over NFS could involve a delay leading to a "text file busy" error
# when trying to run it, so we will copy it over rsync/ssh
ssh "$HOST" mkdir --parents /mnt/khutulun/common/plugin/agent/
rsync "$GOPATH/bin/khutulun-agent" "$HOST:/mnt/khutulun/common/plugin/agent/agent"

ssh "$HOST" mkdir --parents .config/systemd/user/
rsync "$ROOT/assets/systemd/khutulun-agent.service" "$HOST:.config/systemd/user/"

ssh "$HOST" systemctl --user daemon-reload
ssh "$HOST" systemctl --user start khutulun-agent.service
ssh "$HOST" systemctl --user enable khutulun-agent.service
ssh "$HOST" loginctl enable-linger

#khutulun agent add "$HOST" "$HOST"

# journalctl --follow --user --unit khutulun-agent.service
