#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

# sudo dnf install protobuf-compiler protobuf-devel
# go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
# go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

protoc \
	khutulun.proto \
	--proto_path="$ROOT/assets/grpc" \
	--go_out="$ROOT/api" \
	--go-grpc_out="$ROOT/api" \
	--go_opt=paths=source_relative \
	--go-grpc_opt=paths=source_relative
