#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd "$ROOT/assets/tosca/profiles/khutulun"

rm -f "$ROOT/work/khutulun.tar.gz"
tar -czf "$ROOT/work/khutulun.tar.gz" .
khutulun profile delist khutulun --namespace=common || true
khutulun profile register khutulun "$ROOT/work/khutulun.tar.gz" --namespace=common
