#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

khutulun delegate register podman "$GOPATH/bin/khutulun-delegate-podman" --namespace=common -vv
khutulun delegate register ipport "$GOPATH/bin/khutulun-delegate-ipport" --namespace=common
#sleep 5
khutulun profile register khutulun "$ROOT/assets/tosca/profiles/khutulun/" --namespace=common
#khutulun profile register khutulun "$ROOT/khutulun.zip" --namespace=common
khutulun template register hello "$ROOT/examples/hello-world/hello-world.yaml"
khutulun service deploy hello
