// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.19.6
// source: khutulun.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Interaction_Stream int32

const (
	Interaction_NONE   Interaction_Stream = 0
	Interaction_STDIN  Interaction_Stream = 1
	Interaction_STDOUT Interaction_Stream = 2
	Interaction_STDERR Interaction_Stream = 3
	Interaction_SIZE   Interaction_Stream = 4
)

// Enum value maps for Interaction_Stream.
var (
	Interaction_Stream_name = map[int32]string{
		0: "NONE",
		1: "STDIN",
		2: "STDOUT",
		3: "STDERR",
		4: "SIZE",
	}
	Interaction_Stream_value = map[string]int32{
		"NONE":   0,
		"STDIN":  1,
		"STDOUT": 2,
		"STDERR": 3,
		"SIZE":   4,
	}
)

func (x Interaction_Stream) Enum() *Interaction_Stream {
	p := new(Interaction_Stream)
	*p = x
	return p
}

func (x Interaction_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Interaction_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_khutulun_proto_enumTypes[0].Descriptor()
}

func (Interaction_Stream) Type() protoreflect.EnumType {
	return &file_khutulun_proto_enumTypes[0]
}

func (x Interaction_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Interaction_Stream.Descriptor instead.
func (Interaction_Stream) EnumDescriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{21, 0}
}

type DelegateListResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service      *ServiceIdentifier `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	CoercedClout *Clout             `protobuf:"bytes,2,opt,name=coercedClout,proto3" json:"coercedClout,omitempty"`
}

func (x *DelegateListResources) Reset() {
	*x = DelegateListResources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelegateListResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateListResources) ProtoMessage() {}

func (x *DelegateListResources) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateListResources.ProtoReflect.Descriptor instead.
func (*DelegateListResources) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{0}
}

func (x *DelegateListResources) GetService() *ServiceIdentifier {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *DelegateListResources) GetCoercedClout() *Clout {
	if x != nil {
		return x.CoercedClout
	}
	return nil
}

type ProcessService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service      *ServiceIdentifier `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Phase        string             `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Clout        *Clout             `protobuf:"bytes,3,opt,name=clout,proto3" json:"clout,omitempty"`
	CoercedClout *Clout             `protobuf:"bytes,4,opt,name=coercedClout,proto3" json:"coercedClout,omitempty"`
}

func (x *ProcessService) Reset() {
	*x = ProcessService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessService) ProtoMessage() {}

func (x *ProcessService) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessService.ProtoReflect.Descriptor instead.
func (*ProcessService) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessService) GetService() *ServiceIdentifier {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ProcessService) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ProcessService) GetClout() *Clout {
	if x != nil {
		return x.Clout
	}
	return nil
}

func (x *ProcessService) GetCoercedClout() *Clout {
	if x != nil {
		return x.CoercedClout
	}
	return nil
}

type ProcessServiceResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clout *Clout         `protobuf:"bytes,1,opt,name=clout,proto3" json:"clout,omitempty"`
	Next  []*NextService `protobuf:"bytes,2,rep,name=next,proto3" json:"next,omitempty"`
}

func (x *ProcessServiceResult) Reset() {
	*x = ProcessServiceResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessServiceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessServiceResult) ProtoMessage() {}

func (x *ProcessServiceResult) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessServiceResult.ProtoReflect.Descriptor instead.
func (*ProcessServiceResult) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessServiceResult) GetClout() *Clout {
	if x != nil {
		return x.Clout
	}
	return nil
}

func (x *ProcessServiceResult) GetNext() []*NextService {
	if x != nil {
		return x.Next
	}
	return nil
}

type NextService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host    string             `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Service *ServiceIdentifier `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Phase   string             `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
}

func (x *NextService) Reset() {
	*x = NextService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextService) ProtoMessage() {}

func (x *NextService) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextService.ProtoReflect.Descriptor instead.
func (*NextService) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{3}
}

func (x *NextService) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NextService) GetService() *ServiceIdentifier {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *NextService) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type Clout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cbor []byte `protobuf:"bytes,1,opt,name=cbor,proto3" json:"cbor,omitempty"`
	Yaml string `protobuf:"bytes,2,opt,name=yaml,proto3" json:"yaml,omitempty"`
}

func (x *Clout) Reset() {
	*x = Clout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Clout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clout) ProtoMessage() {}

func (x *Clout) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clout.ProtoReflect.Descriptor instead.
func (*Clout) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{4}
}

func (x *Clout) GetCbor() []byte {
	if x != nil {
		return x.Cbor
	}
	return nil
}

func (x *Clout) GetYaml() string {
	if x != nil {
		return x.Yaml
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *structpb.Struct `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{5}
}

func (x *Config) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type Version struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Version) Reset() {
	*x = Version{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{6}
}

func (x *Version) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Namespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{7}
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HostIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GrpcAddress string `protobuf:"bytes,2,opt,name=grpcAddress,proto3" json:"grpcAddress,omitempty"`
}

func (x *HostIdentifier) Reset() {
	*x = HostIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostIdentifier) ProtoMessage() {}

func (x *HostIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostIdentifier.ProtoReflect.Descriptor instead.
func (*HostIdentifier) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{8}
}

func (x *HostIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostIdentifier) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

type PackageType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PackageType) Reset() {
	*x = PackageType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageType) ProtoMessage() {}

func (x *PackageType) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageType.ProtoReflect.Descriptor instead.
func (*PackageType) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{9}
}

func (x *PackageType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PackageIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      *PackageType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Namespace string       `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PackageIdentifier) Reset() {
	*x = PackageIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageIdentifier) ProtoMessage() {}

func (x *PackageIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageIdentifier.ProtoReflect.Descriptor instead.
func (*PackageIdentifier) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{10}
}

func (x *PackageIdentifier) GetType() *PackageType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *PackageIdentifier) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PackageIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddHost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GossipAddress string `protobuf:"bytes,1,opt,name=gossipAddress,proto3" json:"gossipAddress,omitempty"`
}

func (x *AddHost) Reset() {
	*x = AddHost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHost) ProtoMessage() {}

func (x *AddHost) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHost.ProtoReflect.Descriptor instead.
func (*AddHost) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{11}
}

func (x *AddHost) GetGossipAddress() string {
	if x != nil {
		return x.GossipAddress
	}
	return ""
}

type ListPackages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      *PackageType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Namespace string       `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *ListPackages) Reset() {
	*x = ListPackages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPackages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackages) ProtoMessage() {}

func (x *ListPackages) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackages.ProtoReflect.Descriptor instead.
func (*ListPackages) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{12}
}

func (x *ListPackages) GetType() *PackageType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ListPackages) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetPackageFiles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier *PackageIdentifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Coerce     bool               `protobuf:"varint,2,opt,name=coerce,proto3" json:"coerce,omitempty"`
	Paths      []string           `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *GetPackageFiles) Reset() {
	*x = GetPackageFiles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPackageFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageFiles) ProtoMessage() {}

func (x *GetPackageFiles) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageFiles.ProtoReflect.Descriptor instead.
func (*GetPackageFiles) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{13}
}

func (x *GetPackageFiles) GetIdentifier() *PackageIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetPackageFiles) GetCoerce() bool {
	if x != nil {
		return x.Coerce
	}
	return false
}

func (x *GetPackageFiles) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type PackageFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path       string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Executable bool   `protobuf:"varint,2,opt,name=executable,proto3" json:"executable,omitempty"`
}

func (x *PackageFile) Reset() {
	*x = PackageFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageFile) ProtoMessage() {}

func (x *PackageFile) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageFile.ProtoReflect.Descriptor instead.
func (*PackageFile) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{14}
}

func (x *PackageFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PackageFile) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

type PackageContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start *PackageContent_Start `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	File  *PackageFile          `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Bytes []byte                `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *PackageContent) Reset() {
	*x = PackageContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageContent) ProtoMessage() {}

func (x *PackageContent) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageContent.ProtoReflect.Descriptor instead.
func (*PackageContent) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{15}
}

func (x *PackageContent) GetStart() *PackageContent_Start {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *PackageContent) GetFile() *PackageFile {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *PackageContent) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type ServiceIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServiceIdentifier) Reset() {
	*x = ServiceIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceIdentifier) ProtoMessage() {}

func (x *ServiceIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceIdentifier.ProtoReflect.Descriptor instead.
func (*ServiceIdentifier) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{16}
}

func (x *ServiceIdentifier) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListServices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *ListServices) Reset() {
	*x = ListServices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServices) ProtoMessage() {}

func (x *ListServices) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServices.ProtoReflect.Descriptor instead.
func (*ListServices) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{17}
}

func (x *ListServices) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DeployService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Template *PackageIdentifier `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Service  *ServiceIdentifier `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Async    bool               `protobuf:"varint,3,opt,name=async,proto3" json:"async,omitempty"`
}

func (x *DeployService) Reset() {
	*x = DeployService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployService) ProtoMessage() {}

func (x *DeployService) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployService.ProtoReflect.Descriptor instead.
func (*DeployService) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{18}
}

func (x *DeployService) GetTemplate() *PackageIdentifier {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *DeployService) GetService() *ServiceIdentifier {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *DeployService) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

type ResourceIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *ServiceIdentifier `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Type    string             `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name    string             `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Host    string             `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *ResourceIdentifier) Reset() {
	*x = ResourceIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceIdentifier) ProtoMessage() {}

func (x *ResourceIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceIdentifier.ProtoReflect.Descriptor instead.
func (*ResourceIdentifier) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{19}
}

func (x *ResourceIdentifier) GetService() *ServiceIdentifier {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ResourceIdentifier) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceIdentifier) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type ListResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *ServiceIdentifier `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Type    string             `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ListResources) Reset() {
	*x = ListResources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResources) ProtoMessage() {}

func (x *ListResources) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResources.ProtoReflect.Descriptor instead.
func (*ListResources) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{20}
}

func (x *ListResources) GetService() *ServiceIdentifier {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ListResources) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Interaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start  *Interaction_Start `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Stream Interaction_Stream `protobuf:"varint,2,opt,name=stream,proto3,enum=khutulun.Interaction_Stream" json:"stream,omitempty"`
	Bytes  []byte             `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Size   *Interaction_Size  `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Interaction) Reset() {
	*x = Interaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interaction) ProtoMessage() {}

func (x *Interaction) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interaction.ProtoReflect.Descriptor instead.
func (*Interaction) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{21}
}

func (x *Interaction) GetStart() *Interaction_Start {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Interaction) GetStream() Interaction_Stream {
	if x != nil {
		return x.Stream
	}
	return Interaction_NONE
}

func (x *Interaction) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *Interaction) GetSize() *Interaction_Size {
	if x != nil {
		return x.Size
	}
	return nil
}

type InteractionErrorDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExitCode int32  `protobuf:"varint,1,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	Stderr   []byte `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
}

func (x *InteractionErrorDetails) Reset() {
	*x = InteractionErrorDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InteractionErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionErrorDetails) ProtoMessage() {}

func (x *InteractionErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionErrorDetails.ProtoReflect.Descriptor instead.
func (*InteractionErrorDetails) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{22}
}

func (x *InteractionErrorDetails) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *InteractionErrorDetails) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

type PackageContent_Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier *PackageIdentifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
}

func (x *PackageContent_Start) Reset() {
	*x = PackageContent_Start{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageContent_Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageContent_Start) ProtoMessage() {}

func (x *PackageContent_Start) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageContent_Start.ProtoReflect.Descriptor instead.
func (*PackageContent_Start) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{15, 0}
}

func (x *PackageContent_Start) GetIdentifier() *PackageIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

type Interaction_Size struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  uint32 `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Interaction_Size) Reset() {
	*x = Interaction_Size{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interaction_Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interaction_Size) ProtoMessage() {}

func (x *Interaction_Size) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interaction_Size.ProtoReflect.Descriptor instead.
func (*Interaction_Size) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{21, 0}
}

func (x *Interaction_Size) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Interaction_Size) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Interaction_Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier     []string          `protobuf:"bytes,1,rep,name=identifier,proto3" json:"identifier,omitempty"`
	Command        []string          `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Environment    map[string]string `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PseudoTerminal bool              `protobuf:"varint,4,opt,name=pseudoTerminal,proto3" json:"pseudoTerminal,omitempty"`
	InitialSize    *Interaction_Size `protobuf:"bytes,5,opt,name=initialSize,proto3" json:"initialSize,omitempty"`
}

func (x *Interaction_Start) Reset() {
	*x = Interaction_Start{}
	if protoimpl.UnsafeEnabled {
		mi := &file_khutulun_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interaction_Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interaction_Start) ProtoMessage() {}

func (x *Interaction_Start) ProtoReflect() protoreflect.Message {
	mi := &file_khutulun_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interaction_Start.ProtoReflect.Descriptor instead.
func (*Interaction_Start) Descriptor() ([]byte, []int) {
	return file_khutulun_proto_rawDescGZIP(), []int{21, 1}
}

func (x *Interaction_Start) GetIdentifier() []string {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Interaction_Start) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Interaction_Start) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *Interaction_Start) GetPseudoTerminal() bool {
	if x != nil {
		return x.PseudoTerminal
	}
	return false
}

func (x *Interaction_Start) GetInitialSize() *Interaction_Size {
	if x != nil {
		return x.InitialSize
	}
	return nil
}

var File_khutulun_proto protoreflect.FileDescriptor

var file_khutulun_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12,
	0x35, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x63, 0x6f, 0x65, 0x72, 0x63, 0x65,
	0x64, 0x43, 0x6c, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6b,
	0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x74, 0x52, 0x0c, 0x63,
	0x6f, 0x65, 0x72, 0x63, 0x65, 0x64, 0x43, 0x6c, 0x6f, 0x75, 0x74, 0x22, 0xb9, 0x01, 0x0a, 0x0e,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35,
	0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x63,
	0x6c, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6b, 0x68, 0x75,
	0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x74, 0x52, 0x05, 0x63, 0x6c, 0x6f,
	0x75, 0x74, 0x12, 0x33, 0x0a, 0x0c, 0x63, 0x6f, 0x65, 0x72, 0x63, 0x65, 0x64, 0x43, 0x6c, 0x6f,
	0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75,
	0x6c, 0x75, 0x6e, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x74, 0x52, 0x0c, 0x63, 0x6f, 0x65, 0x72, 0x63,
	0x65, 0x64, 0x43, 0x6c, 0x6f, 0x75, 0x74, 0x22, 0x68, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x25, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x74, 0x52,
	0x05, 0x63, 0x6c, 0x6f, 0x75, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e,
	0x4e, 0x65, 0x78, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x04, 0x6e, 0x65, 0x78,
	0x74, 0x22, 0x6e, 0x0a, 0x0b, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x68, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73,
	0x65, 0x22, 0x2f, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x62,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x63, 0x62, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x79, 0x61, 0x6d, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x61,
	0x6d, 0x6c, 0x22, 0x39, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2f, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x23, 0x0a,
	0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x1f, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x0e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x72, 0x70,
	0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x67, 0x72, 0x70, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x21, 0x0a, 0x0b, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x70,
	0x0a, 0x11, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x2f, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x67,
	0x6f, 0x73, 0x73, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x22, 0x57, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x7c, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x3b, 0x0a,
	0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x0a,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f,
	0x65, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x63, 0x6f, 0x65, 0x72,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x22, 0x41, 0x0a, 0x0b, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0xcd, 0x01, 0x0a, 0x0e,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x34,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x1a, 0x44, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x3b,
	0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52,
	0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x11, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x22, 0x95, 0x01, 0x0a, 0x0d, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b,
	0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x22, 0x87, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12,
	0x35, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x22, 0x5a, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xed,
	0x04, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1c, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x2e, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6b, 0x68,
	0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x1a, 0x34, 0x0a,
	0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x1a, 0xb7, 0x02, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x4e, 0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72,
	0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6b,
	0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x73, 0x65, 0x75, 0x64,
	0x6f, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0e, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x12,
	0x3c, 0x0a, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x7a, 0x65,
	0x52, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x1a, 0x3e, 0x0a,
	0x10, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3f, 0x0a,
	0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x44, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x54, 0x44, 0x4f, 0x55, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x44, 0x45,
	0x52, 0x52, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x49, 0x5a, 0x45, 0x10, 0x04, 0x22, 0x4d,
	0x0a, 0x17, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x69,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x69,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x32, 0xaa, 0x06,
	0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e,
	0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x3f, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e,
	0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x30,
	0x01, 0x12, 0x34, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x6b,
	0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3f, 0x0a, 0x0e, 0x6c, 0x69, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x13, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75,
	0x6c, 0x75, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73,
	0x1a, 0x1b, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x30, 0x01, 0x12,
	0x48, 0x0a, 0x10, 0x6c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x1a, 0x15, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x30, 0x01, 0x12, 0x48, 0x0a, 0x0f, 0x67, 0x65, 0x74,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x6b,
	0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x1a, 0x18, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c,
	0x75, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x0f, 0x73, 0x65, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75,
	0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x28, 0x01, 0x12, 0x44, 0x0a, 0x0d, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x2e, 0x6b, 0x68,
	0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x40, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x17, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x48, 0x0a, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x1a, 0x1c, 0x2e, 0x6b,
	0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x30, 0x01, 0x12, 0x3c, 0x0a, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x12, 0x15, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75,
	0x6c, 0x75, 0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a,
	0x15, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x28, 0x01, 0x30, 0x01, 0x32, 0xe6, 0x01, 0x0a, 0x08, 0x44,
	0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75,
	0x6c, 0x75, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x1a, 0x1c, 0x2e, 0x6b, 0x68, 0x75, 0x74,
	0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x30, 0x01, 0x12, 0x4a, 0x0a, 0x0e, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x2e, 0x6b, 0x68,
	0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1e, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e,
	0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3c, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63,
	0x74, 0x12, 0x15, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75, 0x6e, 0x2e, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x15, 0x2e, 0x6b, 0x68, 0x75, 0x74, 0x75,
	0x6c, 0x75, 0x6e, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x6c, 0x69, 0x72, 0x6f, 0x6e, 0x2f, 0x6b, 0x68, 0x75, 0x74, 0x75, 0x6c, 0x75,
	0x6e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_khutulun_proto_rawDescOnce sync.Once
	file_khutulun_proto_rawDescData = file_khutulun_proto_rawDesc
)

func file_khutulun_proto_rawDescGZIP() []byte {
	file_khutulun_proto_rawDescOnce.Do(func() {
		file_khutulun_proto_rawDescData = protoimpl.X.CompressGZIP(file_khutulun_proto_rawDescData)
	})
	return file_khutulun_proto_rawDescData
}

var file_khutulun_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_khutulun_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_khutulun_proto_goTypes = []interface{}{
	(Interaction_Stream)(0),         // 0: khutulun.Interaction.Stream
	(*DelegateListResources)(nil),   // 1: khutulun.DelegateListResources
	(*ProcessService)(nil),          // 2: khutulun.ProcessService
	(*ProcessServiceResult)(nil),    // 3: khutulun.ProcessServiceResult
	(*NextService)(nil),             // 4: khutulun.NextService
	(*Clout)(nil),                   // 5: khutulun.Clout
	(*Config)(nil),                  // 6: khutulun.Config
	(*Version)(nil),                 // 7: khutulun.Version
	(*Namespace)(nil),               // 8: khutulun.Namespace
	(*HostIdentifier)(nil),          // 9: khutulun.HostIdentifier
	(*PackageType)(nil),             // 10: khutulun.PackageType
	(*PackageIdentifier)(nil),       // 11: khutulun.PackageIdentifier
	(*AddHost)(nil),                 // 12: khutulun.AddHost
	(*ListPackages)(nil),            // 13: khutulun.ListPackages
	(*GetPackageFiles)(nil),         // 14: khutulun.GetPackageFiles
	(*PackageFile)(nil),             // 15: khutulun.PackageFile
	(*PackageContent)(nil),          // 16: khutulun.PackageContent
	(*ServiceIdentifier)(nil),       // 17: khutulun.ServiceIdentifier
	(*ListServices)(nil),            // 18: khutulun.ListServices
	(*DeployService)(nil),           // 19: khutulun.DeployService
	(*ResourceIdentifier)(nil),      // 20: khutulun.ResourceIdentifier
	(*ListResources)(nil),           // 21: khutulun.ListResources
	(*Interaction)(nil),             // 22: khutulun.Interaction
	(*InteractionErrorDetails)(nil), // 23: khutulun.InteractionErrorDetails
	(*PackageContent_Start)(nil),    // 24: khutulun.PackageContent.Start
	(*Interaction_Size)(nil),        // 25: khutulun.Interaction.Size
	(*Interaction_Start)(nil),       // 26: khutulun.Interaction.Start
	nil,                             // 27: khutulun.Interaction.Start.EnvironmentEntry
	(*structpb.Struct)(nil),         // 28: google.protobuf.Struct
	(*emptypb.Empty)(nil),           // 29: google.protobuf.Empty
}
var file_khutulun_proto_depIdxs = []int32{
	17, // 0: khutulun.DelegateListResources.service:type_name -> khutulun.ServiceIdentifier
	5,  // 1: khutulun.DelegateListResources.coercedClout:type_name -> khutulun.Clout
	17, // 2: khutulun.ProcessService.service:type_name -> khutulun.ServiceIdentifier
	5,  // 3: khutulun.ProcessService.clout:type_name -> khutulun.Clout
	5,  // 4: khutulun.ProcessService.coercedClout:type_name -> khutulun.Clout
	5,  // 5: khutulun.ProcessServiceResult.clout:type_name -> khutulun.Clout
	4,  // 6: khutulun.ProcessServiceResult.next:type_name -> khutulun.NextService
	17, // 7: khutulun.NextService.service:type_name -> khutulun.ServiceIdentifier
	28, // 8: khutulun.Config.config:type_name -> google.protobuf.Struct
	10, // 9: khutulun.PackageIdentifier.type:type_name -> khutulun.PackageType
	10, // 10: khutulun.ListPackages.type:type_name -> khutulun.PackageType
	11, // 11: khutulun.GetPackageFiles.identifier:type_name -> khutulun.PackageIdentifier
	24, // 12: khutulun.PackageContent.start:type_name -> khutulun.PackageContent.Start
	15, // 13: khutulun.PackageContent.file:type_name -> khutulun.PackageFile
	11, // 14: khutulun.DeployService.template:type_name -> khutulun.PackageIdentifier
	17, // 15: khutulun.DeployService.service:type_name -> khutulun.ServiceIdentifier
	17, // 16: khutulun.ResourceIdentifier.service:type_name -> khutulun.ServiceIdentifier
	17, // 17: khutulun.ListResources.service:type_name -> khutulun.ServiceIdentifier
	26, // 18: khutulun.Interaction.start:type_name -> khutulun.Interaction.Start
	0,  // 19: khutulun.Interaction.stream:type_name -> khutulun.Interaction.Stream
	25, // 20: khutulun.Interaction.size:type_name -> khutulun.Interaction.Size
	11, // 21: khutulun.PackageContent.Start.identifier:type_name -> khutulun.PackageIdentifier
	27, // 22: khutulun.Interaction.Start.environment:type_name -> khutulun.Interaction.Start.EnvironmentEntry
	25, // 23: khutulun.Interaction.Start.initialSize:type_name -> khutulun.Interaction.Size
	29, // 24: khutulun.Agent.getVersion:input_type -> google.protobuf.Empty
	29, // 25: khutulun.Agent.listHosts:input_type -> google.protobuf.Empty
	12, // 26: khutulun.Agent.addHost:input_type -> khutulun.AddHost
	29, // 27: khutulun.Agent.listNamespaces:input_type -> google.protobuf.Empty
	13, // 28: khutulun.Agent.listPackages:input_type -> khutulun.ListPackages
	11, // 29: khutulun.Agent.listPackageFiles:input_type -> khutulun.PackageIdentifier
	14, // 30: khutulun.Agent.getPackageFiles:input_type -> khutulun.GetPackageFiles
	16, // 31: khutulun.Agent.setPackageFiles:input_type -> khutulun.PackageContent
	11, // 32: khutulun.Agent.removePackage:input_type -> khutulun.PackageIdentifier
	19, // 33: khutulun.Agent.deployService:input_type -> khutulun.DeployService
	21, // 34: khutulun.Agent.listResources:input_type -> khutulun.ListResources
	22, // 35: khutulun.Agent.interact:input_type -> khutulun.Interaction
	1,  // 36: khutulun.Delegate.listResources:input_type -> khutulun.DelegateListResources
	2,  // 37: khutulun.Delegate.processService:input_type -> khutulun.ProcessService
	22, // 38: khutulun.Delegate.interact:input_type -> khutulun.Interaction
	7,  // 39: khutulun.Agent.getVersion:output_type -> khutulun.Version
	9,  // 40: khutulun.Agent.listHosts:output_type -> khutulun.HostIdentifier
	29, // 41: khutulun.Agent.addHost:output_type -> google.protobuf.Empty
	8,  // 42: khutulun.Agent.listNamespaces:output_type -> khutulun.Namespace
	11, // 43: khutulun.Agent.listPackages:output_type -> khutulun.PackageIdentifier
	15, // 44: khutulun.Agent.listPackageFiles:output_type -> khutulun.PackageFile
	16, // 45: khutulun.Agent.getPackageFiles:output_type -> khutulun.PackageContent
	29, // 46: khutulun.Agent.setPackageFiles:output_type -> google.protobuf.Empty
	29, // 47: khutulun.Agent.removePackage:output_type -> google.protobuf.Empty
	29, // 48: khutulun.Agent.deployService:output_type -> google.protobuf.Empty
	20, // 49: khutulun.Agent.listResources:output_type -> khutulun.ResourceIdentifier
	22, // 50: khutulun.Agent.interact:output_type -> khutulun.Interaction
	20, // 51: khutulun.Delegate.listResources:output_type -> khutulun.ResourceIdentifier
	3,  // 52: khutulun.Delegate.processService:output_type -> khutulun.ProcessServiceResult
	22, // 53: khutulun.Delegate.interact:output_type -> khutulun.Interaction
	39, // [39:54] is the sub-list for method output_type
	24, // [24:39] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_khutulun_proto_init() }
func file_khutulun_proto_init() {
	if File_khutulun_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_khutulun_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelegateListResources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessServiceResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Clout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Version); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Namespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddHost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPackages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPackageFiles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListServices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Interaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InteractionErrorDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageContent_Start); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Interaction_Size); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_khutulun_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Interaction_Start); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_khutulun_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_khutulun_proto_goTypes,
		DependencyIndexes: file_khutulun_proto_depIdxs,
		EnumInfos:         file_khutulun_proto_enumTypes,
		MessageInfos:      file_khutulun_proto_msgTypes,
	}.Build()
	File_khutulun_proto = out.File
	file_khutulun_proto_rawDesc = nil
	file_khutulun_proto_goTypes = nil
	file_khutulun_proto_depIdxs = nil
}
